# Generated by Django 3.0.7 on 2020-06-07 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200606_1827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='catrgory',
            new_name='category',
        ),
    ]
